#!/usr/bin/env python3

from omnivoice import OmniVoice
import torch
import torchaudio
from datetime import datetime as dt

def read_input():
    file_path = "input.txt"
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()
        lines = text.split('\n\n')
        processed_lines = [line.replace('\n', ' ').strip() for line in lines]
        result = '\n'.join(processed_lines)
        return result

def get_ref_audio():
    import sys
    if len(sys.argv) > 1:
        return sys.argv[1]
    else:
        return "ref.mp3"

model = OmniVoice.from_pretrained(
    "k2-fsa/OmniVoice",
    device_map="cuda",
    dtype=torch.float16
)

input_text = read_input()

audio = model.generate(
    text=input_text,
    ref_audio=get_ref_audio(),
    language="vi",
    speed=1,
    denoise=True,
    num_step=64,
    postprocess_output=True,
    position_temperature=1,
    class_temperature=1
)

torchaudio.save(f"voice-{dt.now().strftime("%Y%m%d%H%M%S")}.wav", audio[0], 24000)
